### ISSUE TITLE
Stop Button Do Not Work When on Pause (Safari)

### ISSUE THREAD

**Issue by ObaoziO** [RITAccess/Glance-data-analyzer#142]
As the audio is playing, press pause, then stop, and play the audio again, it doesn't start from the beginning but continues where the pause was.

**Comment by Rek3650** [comment]
What browser? Working fine in chrome.

**Comment by baozi90** [comment]
Safari, and Firefox is working fine too.

**Comment by smcintosh881** [comment]
I don't think this is an issue then

**Comment by baozi90** [comment]
No, I meant it's not stopping right in Safari, and for Firefox it's working like Chrome is.

**Comment by smcintosh881** [comment]
oh ok
