### ISSUE TITLE
Table Crashes Page With Very Specific Input

### ISSUE THREAD

**Issue by Rek3650** [RITAccess/Glance-data-analyzer#157]
While trying to debug issue #147 I discovered another obscure error. If a user inputs =/\*- and a number (i.e. =/\*-5) the entire page crashes. I have tested other combinations like =/-\* and =\*/- and it does not crash. This is so obscure I'm not even sure if it is necessary to fix. The only reason I found it is because =/\*- are aligned on my keyboard and I was testing non number inputs.

**Comment by smcintosh881** [comment]
I think this has to do with the fact that the table accepts any input if there is an equal sign in front. 
ex. =cats 
is an accepted input. It doesn't break the page like =/*- does but it still should not accept it as input. If you try to put "cats" it will not accept it and revert to the original. I think this is more of an issue with the "=" sign.

**Comment by ObaoziO** [comment]
This link might help: http://www.qodo.co.uk/blog/javascript-restrict-keyboard-character-input/


Also, maybe it has something to do with these lines of code in the image below?

<img width="695" alt="qq20150901-7 2x" src="https://cloud.githubusercontent.com/assets/11864006/9611996/172b82b6-50b1-11e5-8313-9b04768add52.png">

Especially: newVal.charAt(0) == '='

**Comment by erl7902** [comment]
That's from my math in table code, just the way it's parsed. I could take a crack at fixing it over the weekend

**Comment by jmiller656** [comment]
Adding to this, dividing by zero is also allowed. It turns the cell into infinity and breaks the graph.

**Comment by erl7902** [comment]
Rats. Sorry. I won't get to it until probably thursday or Friday.

**Comment by jmiller656** [comment]
Looks like I've fixed this for infinite inputs and all instances of non mathematical inputs like =cats

**Comment by jmiller656** [comment]
Solved the problem with =/*- . I think it was just a dumb javascript thing where for some reason NaN was accepted by the regex used. Either way, all I had to do was check the array (array being the variable x in that particular section of the code) to see if it contained NaN. If so, just return x as it is, then it is considered not enumerable and the value returns to what it normally was.

**Comment by erl7902** [comment]
@jmiller656  is this closed?

**Comment by jmiller656** [comment]
Yeah. I'll close it now.
