### ISSUE TITLE
Page Became Blank When Loading (Safari)

### ISSUE THREAD

**Issue by ObaoziO** [RITAccess/Glance-data-analyzer#165]
So far, I have only encounter it once:

When I load/reload the page, the page became blank with only the tannish background image and nothing else appears on the page.

Along with that, I've also got the error below:
<img width="1166" alt="screen shot 2015-10-30 at 10 46 29" src="https://cloud.githubusercontent.com/assets/11864006/10848793/f62f76f0-7ef3-11e5-91e6-0add22129d52.png">

Note: 
The page seemed to automatically load correctly after waiting for sometime. (Was on fullscreen when blank page loaded, opened inspector and exit out of fullscreen. Since my Web Inspector is on a separate window from the actual page, I went back and forth to exit out fullscreen and the blank page became normal the next time I look at it.)

**Comment by Outofit08** [comment]
Unable to recreate this bug using Safari

**Comment by Outofit08** [comment]
closing this issue, as it seems to have been due to user tools.
