### ISSUE TITLE
Button Hover Feature Do Not Work (Safari)

### ISSUE THREAD

**Issue by ObaoziO** [RITAccess/Glance-data-analyzer#167]
The hovering feature for the buttons do not work, not at all.

Supposedly, when hovered over a button, the button and text color will all became inverted to it's normal state. In other words, button background color is black and text color is white:
- background-color: #000;
- color: #FFF;

On the other hand, as you click on the buttons, the inverted colors would appear. 

(Related to issue #164, #166, and #168.)

**Comment by Outofit08** [comment]
This feature works as designed now. Buttons have inverted highlight color black and white when hovering or not hovering. The feature can be removed if needed.
