### ISSUE TITLE
Load CSV Hover Style Remained After Clicked (Safari)

### ISSUE THREAD

**Issue by ObaoziO** [RITAccess/Glance-data-analyzer#168]
After clicking on the Load CSV button, a pop up for loading files appears, click Cancel on the load file pop up, the Load CSV button css style stays as hover-over state even though the mouse was not hovering over the button.

(Related to issue #164, #166, and #167.)

**Comment by Outofit08** [comment]
This has been resolved. 

Tested on Safari mac os x  and up
