### ISSUE TITLE
ChartJs2 branch: X-axis labels

### ISSUE THREAD

**Issue by jmiller656** [RITAccess/Glance-data-analyzer#170]
In the ChartJs2.0 branch, when a scatterplot is made, the x-axis is automatically labeled as numbers instead of with the labels in the table

**Comment by Outofit08** [comment]
Cant replicate issue. Will close if no objections.

**Comment by Remixt** [comment]
I'll give it a shot



Sent from my T-Mobile 4G LTE Device


-------- Original message --------

**Comment by Outofit08** [comment]
Ya let me know Clayton if you find an error.

**Comment by Remixt** [comment]
I haven't been able to replicate it either.

**Comment by Outofit08** [comment]
Ya it may have been something they fixed. Im gonna close that issue.
