### ISSUE TITLE
Sonification doesn't match up to data

### ISSUE THREAD

**Issue by erl7902** [RITAccess/Glance-data-analyzer#175]
Not sure if it's just an issue on the live version of the site but there are several issues with sonification not actually matching the data. It takes uploading/creating two or three different graphs before it lines up

**Comment by retrogamer80s** [comment]
Yikes!

Is there a recent push that seemed to cause this?

Steph

**Comment by erl7902** [comment]
I don't think so - honestly I'm not sure the last time anyone tested sonification, since it was finished a while ago. I was only looking into it because I'm demoing it for my professional communications class. @jmiller656 might have an idea

**Comment by jmiller656** [comment]
I'll be able to check this out tomorrow. Have a few ideas as to what could be causing this. Should be able to fix it relatively quickly

**Comment by jmiller656** [comment]
Ok found the problem. This was caused by the recent push involving the median. The dataset was being sorted before the sonification library built the notes, resulting in the data always playing in sorted order.
