### ISSUE TITLE
Graph Data

### ISSUE THREAD

**Issue by Outofit08** [RITAccess/Glance-data-analyzer#179]
Graph data section has four editable objects: Circle, Square, Parallelogram,  and Triangle. 
These objects have a check box and an empty by default box. Check box will remove designated line from the graph but this line is labeled by one of the four objects and not by the row name. 

There seems to be no point to the empty default boxes they have no editing power when manipulated no matter what number is placed the graph is not changed. 
If these boxes are meant to just be records of what is on the graph and not meant to be an editing tool then we need a better way of getting that information out.

**Comment by retrogamer80s** [comment]
Hi,

Let's leave it there for now unless it is causing a problem.

Steph
